### ISSUE TITLE
Revert file rename

### ISSUE THREAD

**Issue by RobLoach** [libretro-thumbnails/Thomson_-_MOTO#5]
Either revert the file non-ascii names or fix the names in RA.

Have accent Chara there replaced in RA during rhumbnail detection.

**Comment by RobLoach** [comment]
@Zlika Revert made... The packs should be rebuilt within the next few days. Keep a watch on http://thumbnailpacks.libretro.com/?fdsasdfsdsadsfd

**Comment by Zlika** [comment]
Hi @RobLoach. The latest pack (from 2 days ago) is working correctly, the images are downloaded, even when their name include accents. I only tested on Linux though.
